# Generated by Django 5.0.8 on 2024-08-11 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfgrade', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradedpart',
            name='grade_guess',
        ),
        migrations.RemoveField(
            model_name='gradedpart',
            name='guess_confidence',
        ),
        migrations.AlterField(
            model_name='assignedproblem',
            name='assignment',
            field=models.ForeignKey(help_text='The assignment this problem is part of.', on_delete=django.db.models.deletion.CASCADE, to='selfgrade.assignment'),
        ),
    ]
