# Generated by Django 5.0.8 on 2024-08-08 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfgrade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='initial_submission',
            field=models.FileField(blank=True, help_text='PDF file of the initial submission.', null=True, upload_to='initial_submissions/'),
        ),
    ]
