# Generated by Django 5.0.8 on 2024-08-08 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selfgrade', '0002_submission_initial_submission'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assignedproblem',
            unique_together={('assignment', 'number'), ('assignment', 'problem')},
        ),
    ]
