# Generated by Django 5.0.8 on 2024-08-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfgrade', '0002_remove_gradedpart_grade_guess_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gradedpart',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='submission',
            name='reviewer_comments',
            field=models.TextField(blank=True, help_text='Comments from the reviewer (TA or grader).'),
        ),
    ]
