# Generated by Django 5.0.8 on 2024-08-12 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfgrade', '0004_submission_reviewed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='shortname',
            field=models.CharField(default='PHYS-511', help_text='A shorter name', max_length=10),
            preserve_default=False,
        ),
    ]
