# Generated by Django 5.0.8 on 2024-08-26 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfgrade', '0005_course_shortname'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='description',
            field=models.TextField(blank=True, help_text='A description of the assignment.'),
        ),
    ]
