# Generated by Django 5.0.8 on 2024-08-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfgrade', '0006_alter_problem_solution_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='solution_pdf',
            field=models.FileField(blank=True, help_text='PDF file containing the assignment solution.', upload_to='assignment_solutions/'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='statement_pdf',
            field=models.FileField(blank=True, help_text='PDF file containing the assignment statement.', upload_to='assignment_statements/'),
        ),
    ]
