# Generated by Django 5.0.8 on 2024-11-17 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfgrade', '0008_material'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='material',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
    ]
