# Generated by Django 5.0.8 on 2024-12-28 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfgrade', '0010_alter_assignment_options_assignedpart_rubric_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of this grade item schema', max_length=50)),
                ('max_points', models.PositiveIntegerField(help_text='The total number of points possible')),
            ],
        ),
        migrations.CreateModel(
            name='SchemaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of this grade', max_length=25)),
                ('points', models.PositiveIntegerField(help_text='The number of points this grade is worth.')),
                ('schema', models.ForeignKey(help_text='The schema this item belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='selfgrade.gradeschema')),
            ],
        ),
    ]
