# Generated by Django 5.0.8 on 2024-12-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfgrade', '0011_gradeschema_schemaitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradeschema',
            name='description',
            field=models.TextField(blank=True, help_text='The description of this grade schema'),
        ),
        migrations.AddField(
            model_name='schemaitem',
            name='description',
            field=models.TextField(blank=True, help_text='The description of this grade schema item'),
        ),
    ]
