# Generated by Django 5.0.8 on 2024-12-28 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfgrade', '0013_rename_gradeschema_schema_remove_assignedpart_points_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignedpart',
            options={'ordering': ('order',)},
        ),
        migrations.AlterUniqueTogether(
            name='assignedpart',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='assignedpart',
            name='name',
            field=models.CharField(default='name', help_text='The name of this part.', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignedpart',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignedpart',
            name='number',
            field=models.PositiveIntegerField(help_text='The order of this part within the problem.  Deprecated.'),
        ),
    ]
