# Generated by Django 5.0.8 on 2024-12-28 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfgrade', '0014_alter_assignedpart_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('name', models.CharField(help_text='The name of this part.', max_length=30)),
                ('rubric', models.TextField(blank=True, help_text='A rubric for the grading of this part.')),
                ('assignment', models.ForeignKey(help_text='The assignment this part belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='selfgrade.assignment')),
                ('schema', models.ForeignKey(help_text='The grading scheme for this item.', on_delete=django.db.models.deletion.CASCADE, to='selfgrade.schema')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
    ]
