# Generated by Django 5.0.8 on 2024-12-30 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfgrade', '0015_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='type',
            field=models.CharField(choices=[('ST', 'Student'), ('IN', 'Instructor')], default='ST', max_length=2),
        ),
        migrations.AlterField(
            model_name='part',
            name='assignment',
            field=models.ForeignKey(help_text='The assignment this part belongs to.', on_delete=django.db.models.deletion.CASCADE, to='selfgrade.assignment'),
        ),
    ]
