# Generated by Django 5.0.8 on 2024-12-30 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfgrade', '0016_registration_type_alter_part_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradedpart',
            name='part',
            field=models.ForeignKey(default=0, help_text='The specific part being graded.', on_delete=django.db.models.deletion.CASCADE, to='selfgrade.part'),
            preserve_default=False,
        ),
    ]
