# Generated by Django 5.0.8 on 2024-12-31 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfgrade', '0018_alter_gradedpart_assigned_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='comments',
            field=models.TextField(blank=True, help_text='Comments from the student.'),
        ),
        migrations.AlterField(
            model_name='gradedpart',
            name='assigned_part',
            field=models.ForeignKey(help_text='The specific part being graded (deprecated).', null=True, on_delete=django.db.models.deletion.CASCADE, to='selfgrade.assignedpart'),
        ),
    ]
