# Generated by Django 5.0.8 on 2024-12-31 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfgrade', '0019_submission_comments_alter_gradedpart_assigned_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='type',
            field=models.CharField(choices=[('FL', 'Full LMS'), ('AO', 'Assignments only')], default='AO', max_length=2),
        ),
    ]
