# Generated by Django 5.0.8 on 2024-12-31 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfgrade', '0020_course_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradedpart',
            name='grade',
            field=models.PositiveSmallIntegerField(blank=True, help_text='The actual grade given by the grader for this part. Null distinct from zero.', null=True),
        ),
        migrations.AlterField(
            model_name='gradedpart',
            name='self_grade',
            field=models.PositiveSmallIntegerField(blank=True, help_text="The student's self-assessment grade for this part.  Null distinct from zero.", null=True),
        ),
        migrations.AlterUniqueTogether(
            name='schemaitem',
            unique_together={('points', 'schema')},
        ),
    ]
