# Generated by Django 5.0.8 on 2024-12-31 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfgrade', '0021_alter_gradedpart_grade_alter_gradedpart_self_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradedpart',
            name='assigned_part',
            field=models.ForeignKey(blank=True, help_text='The specific part being graded (deprecated).', null=True, on_delete=django.db.models.deletion.CASCADE, to='selfgrade.assignedpart'),
        ),
    ]
